export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const FETCH_COURSE_CATEGORIES = "FETCH_COURSE_CATEGORIES";
export const FETCH_COURSE_CATEGORIES_DETAIL = "FETCH_COURSE_CATEGORIES_DETAIL";
export const CLEAR_COURSE_CATEGORIES_DETAIL = "CLEAR_COURSE_CATEGORIES_DETAIL";
export const FETCH_COURSE_STUDENTS = "FETCH_COURSE_STUDENTS";
export const FETCH_UNREGISTERED_COURSES = "FETCH_UNREGISTERED_COURSES";
export const FETCH_PENDING_COURSES = "FETCH_PENDING_COURSES";
export const FETCH_APPROVED_COURSES = "FETCH_APPROVED_COURSES";
export const FETCH_UNREGISTERED_STUDENTS = "FETCH_UNREGISTERED_STUDENTS";
export const FETCH_PENDING_STUDENTS = "FETCH_PENDING_STUDENTS";
export const FETCH_APPROVED_STUDENTS = "FETCH_APPROVED_STUDENTS";
export const FETCH_COURSE_ID = "FETCH_COURSE_ID";
export const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";
export const FETCH_ACCESS_TOKEN = "FETCH_ACCESS_TOKEN";
export const SIGN_OUT = "SIGN_OUT";
export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const FETCH_COURSE_RESULT = "FETCH_COURSE_RESULT";
export const FETCH_USER_INFO = "FETCH_USER_INFO";





